### ISSUE TITLE
Does this work when whole .travis.yml is a matrix?

### ISSUE THREAD

**Issue by cben** [patch-graph/gitjection#13]
Turns out things like `language:`, and steps like `install:`, `script:` etc. can all live inside the matrix.

example: https://github.com/ManageIQ/manageiq-v2v/blob/8985419ea0c2b6dd29c520feaba335da12043302/.travis.yml
```
matrix:
  include:
  - name: "Node.js: 12"
    language: node_js
    cache: yarn
    node_js:
    - '12' # current stable
    script: yarn test --runInBand
  - name: "Ruby: 2.5.8"
    language: ruby
    cache: bundler
    rvm:
    - 2.5.8
    addons:
      postgresql: '10'
    install: bin/setup
    after_script: bin/ci/after_script
  - name: "Ruby: 2.6.6"
    language: ruby
    rvm:
    - 2.6.6
    cache: bundler
    addons:
      postgresql: '10'
    install: bin/setup
    after_script: bin/ci/after_script
```
